// tslint:disable
/**
 * Trading.ServiceManagerUtils.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApprovalStatus
 */
export interface ApprovalStatus {
  /**
   * @type {string}
   * @memberof ApprovalStatus
   */
  Approver?: string;
  /**
   * @type {string}
   * @memberof ApprovalStatus
   */
  Status?: string;
}
