// tslint:disable
/**
 * Trading.ServiceManagerUtils.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface IncidentRecord
 */
export interface IncidentRecord {
  /**
   * @type {string}
   * @memberof IncidentRecord
   */
  Id?: string;
  /**
   * @type {string}
   * @memberof IncidentRecord
   */
  Title?: string;
  /**
   * @type {string}
   * @memberof IncidentRecord
   */
  Description?: string;
  /**
   * @type {string}
   * @memberof IncidentRecord
   */
  Urgency?: string;
  /**
   * @type {string}
   * @memberof IncidentRecord
   */
  Impact?: string;
  /**
   * @type {number}
   * @memberof IncidentRecord
   */
  Priority?: number;
  /**
   * @type {string}
   * @memberof IncidentRecord
   */
  AffectedUser?: string;
  /**
   * @type {string}
   * @memberof IncidentRecord
   */
  ClassificationCategory?: string;
  /**
   * @type {string}
   * @memberof IncidentRecord
   */
  SupportGroup?: string;
}
