// tslint:disable
/**
 * Trading.ServiceManagerUtils.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RiskQuestions
 */
export interface RiskQuestions {
  /**
   * @type {boolean}
   * @memberof RiskQuestions
   */
  Question1?: boolean;
  /**
   * @type {boolean}
   * @memberof RiskQuestions
   */
  Question2?: boolean;
  /**
   * @type {boolean}
   * @memberof RiskQuestions
   */
  Question3?: boolean;
  /**
   * @type {boolean}
   * @memberof RiskQuestions
   */
  Question4?: boolean;
  /**
   * @type {boolean}
   * @memberof RiskQuestions
   */
  Question5?: boolean;
  /**
   * @type {boolean}
   * @memberof RiskQuestions
   */
  Question6?: boolean;
}
