// tslint:disable
/**
 * Trading.ServiceManagerUtils.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SyncComment
 */
export interface SyncComment {
  /**
   * @type {string}
   * @memberof SyncComment
   */
  Title?: string;
  /**
   * @type {string}
   * @memberof SyncComment
   */
  EnteredDate?: string;
  /**
   * @type {string}
   * @memberof SyncComment
   */
  AuthorIdentity?: string;
  /**
   * @type {string}
   * @memberof SyncComment
   */
  Comment?: string;
  /**
   * @type {number}
   * @memberof SyncComment
   */
  CommentDataSource?: SyncCommentCommentDataSourceEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum SyncCommentCommentDataSourceEnum {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
}
